# To use:
#     pre-commit run -a

# Or:
#     pre-commit install (runs every time you commit in git)

# To update hooks:
#     pre-commit autoupdate

# See https://github.com/pre-commit/pre-commit

repos:

  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude_types: [rst]
      - id: fix-byte-order-marker

  # Python hooks
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        args: [--line-length=130]

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        args: ["--max-line-length", "130"]

  # C/C++ linting and formatting
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6  # Match your clang-format version, can update
    hooks:
      - id: clang-format
        args: ["-style=Google"]  # or "LLVM", "Mozilla", etc.
        files: \.(c|cpp|h|hpp)$

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        args: [-checks=clang-diagnostic-return-type]
        files: src/.*\.c

  # Spellcheck in comments and docs
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: ['--write-changes']
        exclude: CHANGELOG\.rst|\.(svg|pyc)$
